/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartx.du;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author saif_m_dhrubo
 */
public class DepartmentOffice extends javax.swing.JFrame {

    public static HashMap<Integer, data> sdata = new HashMap<>();
    static boolean admitReceived = false;

    /**
     * Creates new form DepartmentOffice
     */
    public DepartmentOffice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        yearComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        semesterComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        maj1_TextField = new javax.swing.JTextField();
        maj1_att = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        maj2_TextField = new javax.swing.JTextField();
        maj2_att = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        maj3_TextField = new javax.swing.JTextField();
        maj3_att = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        min1_TextField = new javax.swing.JTextField();
        min1_att = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        min2_TextField = new javax.swing.JTextField();
        min2_att = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        min3_TextField = new javax.swing.JTextField();
        min3_att = new javax.swing.JTextField();
        forward2server_Button = new javax.swing.JButton();
        storeButton = new javax.swing.JButton();
        fetchDataButton = new javax.swing.JButton();
        loadSreverDataButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        logOutButton = new javax.swing.JButton();
        rollTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        admitCardButton = new javax.swing.JButton();
        saveInfoButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        dept_ComboBox = new javax.swing.JComboBox<>();
        helpButton = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(44, 44, 59));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(234, 232, 217));
        jLabel4.setText("Department Office");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        jLabel1.setText("Select Year");

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "3rd", "4th" }));

        jLabel2.setText("Select Semester");

        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd" }));

        jLabel3.setText("Roll");

        jSeparator1.setBackground(new java.awt.Color(46, 46, 46));
        jSeparator1.setForeground(new java.awt.Color(39, 48, 73));

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Attendance Percentage (%)");

        jLabel7.setText("Major Course - I");

        maj1_att.setText("0.0");

        jLabel8.setText("Major Course - II");

        maj2_att.setText("0.0");

        jLabel9.setText("Major Course - III");

        maj3_att.setText("0.0");

        jLabel10.setText("Minor Course - I");

        min1_att.setText("0.0");

        jLabel11.setText("Minor Course - II");

        min2_att.setText("0.0");

        jLabel12.setText("Minor Course - III");

        min3_att.setText("0.0");

        forward2server_Button.setText("Forward to Server");
        forward2server_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forward2server_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forward2server_ButtonMouseClicked(evt);
            }
        });
        forward2server_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forward2server_ButtonActionPerformed(evt);
            }
        });

        storeButton.setText("Store");
        storeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        storeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storeButtonMouseClicked(evt);
            }
        });

        fetchDataButton.setText("Fetch Data");
        fetchDataButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fetchDataButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fetchDataButtonMouseClicked(evt);
            }
        });

        loadSreverDataButton.setText("Load Data from Server");
        loadSreverDataButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loadSreverDataButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadSreverDataButtonMouseClicked(evt);
            }
        });
        loadSreverDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadSreverDataButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Name");

        logOutButton.setText("Log Out");
        logOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
        });

        jLabel15.setText("No. of Courses");

        admitCardButton.setText("Admit Card Generation");
        admitCardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        admitCardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admitCardButtonMouseClicked(evt);
            }
        });

        saveInfoButton.setText("Save All Information");
        saveInfoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveInfoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveInfoButtonMouseClicked(evt);
            }
        });

        jLabel13.setText("Select Dept.");

        dept_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science and Engineering", "IBA", "Pharmacy", "IIT", "Genetic Engineering and Biotechnology", "Nuclear Engineering", "Robotics and Mechatronics Engineering", "Electrical and Electronic Engineering", "MIcrobiology", "Applied Chemistry and Chemical Engineering", "Finance", "Economics", "International Relations", "Public Administration", "English Literature", "Marketing", "Mass Communication and Journalism", "Political Science", "Development Studies", "Law", " ", " ", " ", " " }));
        dept_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dept_ComboBoxActionPerformed(evt);
            }
        });

        helpButton.setText("Help");
        helpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(forward2server_Button)
                                    .addComponent(maj1_att, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maj2_att, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maj3_att, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(min1_att, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(min2_att, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(min3_att, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(31, 31, 31))))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(rollTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fetchDataButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(admitCardButton)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dept_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 226, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(250, 250, 250)
                                .addComponent(loadSreverDataButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(helpButton)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(min3_TextField))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel9))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(maj1_TextField)
                                        .addComponent(maj2_TextField)
                                        .addComponent(maj3_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel11))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(min2_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                                        .addComponent(min1_TextField))))
                            .addComponent(logOutButton, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(saveInfoButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(storeButton)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(helpButton)
                    .addComponent(loadSreverDataButton))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(dept_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admitCardButton)
                    .addComponent(jLabel3)
                    .addComponent(rollTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fetchDataButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(maj1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maj1_att, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(maj2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maj2_att, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(maj3_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maj3_att, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(min1_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(min1_att, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(min2_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(min2_att, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(min3_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(min3_att, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(storeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveInfoButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(logOutButton)
                            .addComponent(forward2server_Button))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void forward2server_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forward2server_ButtonActionPerformed


    }//GEN-LAST:event_forward2server_ButtonActionPerformed

    private void storeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeButtonMouseClicked

        try {

            int n = Integer.parseInt(rollTextField.getText());

            data d = sdata.get(n);

            d.maj1 = maj1_TextField.getText();
            d.maj2 = maj2_TextField.getText();
            d.maj3 = maj3_TextField.getText();
            d.min1 = min1_TextField.getText();
            d.min2 = min2_TextField.getText();
            d.min3 = min3_TextField.getText();

            d.maj1_attendance = Double.parseDouble(maj1_att.getText());
            d.maj2_attendance = Double.parseDouble(maj2_att.getText());
            d.maj3_attendance = Double.parseDouble(maj3_att.getText());
            d.min1_attendance = Double.parseDouble(min1_att.getText());
            d.min2_attendance = Double.parseDouble(min2_att.getText());
            d.min3_attendance = Double.parseDouble(min3_att.getText());

            int cn = Integer.parseInt(jTextField2.getText());

            double per = (d.min1_attendance + d.min2_attendance + d.min3_attendance + d.maj1_attendance + d.maj2_attendance + d.maj3_attendance) / (double) cn;

            if (per > 60.0) {
                d.eligibility = true;
                Mailer m1 = new Mailer();
                m1.send("smartxdu@gmail.com", "csedu220754", d.email, "Admit Card of Roll : " + rollTextField.getText(), "Hi " + d.name + ",\n" + "You are eligible for attending in semester final exam. Please, complete your payment and provide TrxID in reply\nThanks,\n" + "Department of " + d.department);
                JOptionPane.showMessageDialog(rootPane, "Eligibility mail is sent to " + d.name);
            }
            sdata.put(n, d);

        } catch (Exception e) {
        }


    }//GEN-LAST:event_storeButtonMouseClicked

    private void forward2server_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forward2server_ButtonMouseClicked
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to submit your data?", "Warning!", dialogButton);
            if (dialogResult == 0) {

                SimpleClient sc = new SimpleClient();

                sc.sendh(sdata, 2002);
                JOptionPane.showMessageDialog(rootPane, "All data has been forwarded to server");

            } else {
                System.out.println("Not sure");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_forward2server_ButtonMouseClicked

    private void fetchDataButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fetchDataButtonMouseClicked
        try {

            int n = Integer.parseInt(rollTextField.getText());

            data d = sdata.get(n);
            dept_ComboBox.setSelectedItem(d.department);
            nameTextField.setText(d.name);
            yearComboBox.setSelectedItem(d.year);
            semesterComboBox.setSelectedItem(d.semester);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_fetchDataButtonMouseClicked

    private void loadSreverDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadSreverDataButtonActionPerformed

    }//GEN-LAST:event_loadSreverDataButtonActionPerformed

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        // TODO add your handling code here:
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to logout?", "Confirmation!", dialogButton);
            if (dialogResult == 0) {
                LoginWindow l1 = new LoginWindow();
                l1.setVisible(true);

                dispose();

            } else {
                System.out.println("Not sure");
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_logOutButtonMouseClicked

    private void loadSreverDataButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadSreverDataButtonMouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to load data from server?\nYou can do it only once", "Warning!", dialogButton);
        if (dialogResult == 0) {
            SimpleClient sc = new SimpleClient();
            sdata = sc.receive(2005);

            JOptionPane.showMessageDialog(rootPane, "Data loaded from Server");
        } else {
            System.out.println("Data Not Loaded");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_loadSreverDataButtonMouseClicked

    private void admitCardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admitCardButtonMouseClicked
        if (admitReceived == false) {
            SimpleClient sc = new SimpleClient();
            sdata = sc.receive(2008);
            admitReceived = true;
            AdmitCard a1 = new AdmitCard();
            a1.setVisible(true);
        } else {
            AdmitCard a1 = new AdmitCard();
            a1.setVisible(true);
        }
        dispose();
    }//GEN-LAST:event_admitCardButtonMouseClicked

    private void dept_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dept_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dept_ComboBoxActionPerformed

    private void saveInfoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveInfoButtonMouseClicked
        //String dep = (String) dept_ComboBox.getSelectedItem();
        sdata.entrySet().forEach((entry) -> {
            try {
                Integer n = entry.getKey();
                data d = entry.getValue();
                //  if (d.department.equals(dep)) {

                String path = "/home/saif_m_dhrubo/SmartX Du/DeptData/" + String.valueOf(n) + ".txt";
                System.out.println(path);
                File f = new File(path);

                try {
                    f.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(SignUpWindow.class.getName()).log(Level.SEVERE, null, ex);
                }

                FileWriter writer;
                try {
                    writer = new FileWriter(f);
                    writer.write(d.roll + "\n" + d.regnum + "\n" + d.session + "\n" + d.department + "\n" + d.name + "\n" + d.father + "\n" + d.mother + "\n" + d.dob + "\n" + d.username + "\n" + d.password + "\n" + d.hall + "\n" + d.year + "\n" + d.semester + "\n" + d.email + "\n" + d.residentialStatus + "\n" + d.roomNumber + "\n" + d.maj1 + "\n" + d.maj1_attendance + "\n" + d.maj2 + "\n" + d.maj2_attendance + "\n" + d.maj3 + "\n" + d.maj3_attendance + "\n" + d.min1 + "\n" + d.min1_attendance + "\n" + d.min2 + "\n" + d.min2_attendance + "\n" + d.min3 + "\n" + d.min3_attendance + "\n" + d.hallDuePaid + d.eligibility + "\n" + d.transactionID + "\n" + d.paymentClear + "\n");
                    writer.flush();
                    writer.close();
                } catch (IOException ex) {
                    Logger.getLogger(SignUpWindow.class.getName()).log(Level.SEVERE, null, ex);
                }

                // }
            } catch (Exception e) {
            }

        });// TODO add your handling code here:
    }//GEN-LAST:event_saveInfoButtonMouseClicked

    private void helpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Firstly you have to load data from server. Then you can fetch data of any specific roll.\nAfter confirming attendence percentage of the selected student store it and then forward it to server.");
    }//GEN-LAST:event_helpButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepartmentOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepartmentOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepartmentOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepartmentOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepartmentOffice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admitCardButton;
    private javax.swing.JComboBox<String> dept_ComboBox;
    private javax.swing.JButton fetchDataButton;
    private javax.swing.JButton forward2server_Button;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton loadSreverDataButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JTextField maj1_TextField;
    private javax.swing.JTextField maj1_att;
    private javax.swing.JTextField maj2_TextField;
    private javax.swing.JTextField maj2_att;
    private javax.swing.JTextField maj3_TextField;
    private javax.swing.JTextField maj3_att;
    private javax.swing.JTextField min1_TextField;
    private javax.swing.JTextField min1_att;
    private javax.swing.JTextField min2_TextField;
    private javax.swing.JTextField min2_att;
    private javax.swing.JTextField min3_TextField;
    private javax.swing.JTextField min3_att;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField rollTextField;
    private javax.swing.JButton saveInfoButton;
    private javax.swing.JComboBox<String> semesterComboBox;
    private javax.swing.JButton storeButton;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
