/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartx.du;

import java.io.*;
import java.util.HashMap;
import java.util.logging.*;
import javax.swing.JOptionPane;

/**
 *
 * @author saif_m_dhrubo
 */
public class ExamControllerOffice extends javax.swing.JFrame {

    public static HashMap<Integer, data> sdata = new HashMap<>();

    /**
     * Creates new form ExamControllerOffice
     */
    public ExamControllerOffice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        loadServerDataButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fetchDataButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hallTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        deptTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        yearTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        semesterTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        trxIDTextField = new javax.swing.JTextField();
        paymentCheckBox = new javax.swing.JCheckBox();
        storeButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        helpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(202, 60, 62));
        jPanel1.setForeground(new java.awt.Color(237, 39, 39));

        jLabel1.setBackground(new java.awt.Color(249, 251, 251));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(243, 254, 234));
        jLabel1.setText("Exam Controller Office");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(369, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        loadServerDataButton.setText("Load Data from Server");
        loadServerDataButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loadServerDataButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadServerDataButtonMouseClicked(evt);
            }
        });
        loadServerDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadServerDataButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Roll");

        fetchDataButton.setText("Fetch Data");
        fetchDataButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fetchDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchDataButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Name");

        jLabel4.setText("Hall");

        jLabel5.setText("Department");

        jLabel6.setText("Year");

        jLabel7.setText("Semester");

        jLabel8.setText("(Payment Information)");

        jLabel9.setText("Mobile Banking Transaction ID");

        paymentCheckBox.setText("Payment Clear");

        storeButton.setText("Store");
        storeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        storeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Forward to Server");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        logOutButton.setText("Log Out");
        logOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
        });

        helpButton.setText("Help");
        helpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(320, 320, 320)
                                    .addComponent(loadServerDataButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel2)
                                    .addGap(6, 6, 6)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fetchDataButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nameTextField)
                                                .addComponent(hallTextField)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel5))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(deptTextField)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(semesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 0, Short.MAX_VALUE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(340, 340, 340)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(348, 348, 348)
                                .addComponent(storeButton)))
                        .addGap(0, 248, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(helpButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(logOutButton, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paymentCheckBox)
                                    .addComponent(trxIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton)
                .addGap(9, 9, 9)
                .addComponent(loadServerDataButton)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fetchDataButton)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hallTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(deptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(semesterTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(trxIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(paymentCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(storeButton)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(logOutButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadServerDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadServerDataButtonActionPerformed

    }//GEN-LAST:event_loadServerDataButtonActionPerformed

    private void fetchDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchDataButtonActionPerformed
        // TODO add your handling code here:
        try {
            int n = Integer.parseInt(jTextField1.getText());

            data d = sdata.get(n);

            nameTextField.setText(d.name);
            yearTextField.setText(d.year);
            hallTextField.setText(d.hall);
            deptTextField.setText(d.department);
            semesterTextField.setText(d.semester);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_fetchDataButtonActionPerformed

    private void storeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        int n = Integer.parseInt(jTextField1.getText());

        data d = sdata.get(n);

        d.transactionID = Integer.parseInt(trxIDTextField.getText());

        if (paymentCheckBox.isSelected()) {
            d.paymentClear = true;
        }

        sdata.put(n, d);

        String path = "/home/saif_m_dhrubo/SmartX Du/DeptData/" + String.valueOf(n) + ".txt";
        System.out.println(path);
        File f = new File(path);

        try {
            f.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(SignUpWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

        FileWriter writer;
        try {
            writer = new FileWriter(f);
            writer.write(d.roll + "\n" + d.regnum + "\n" + d.session + "\n" + d.department + "\n" + d.name + "\n" + d.father + "\n" + d.mother + "\n" + d.dob + "\n" + d.username + "\n" + d.password + "\n" + d.hall + "\n" + d.year + "\n" + d.semester + "\n" + d.email + "\n" + d.residentialStatus + "\n" + d.roomNumber + "\n" + d.maj1 + "\n" + d.maj1_attendance + "\n" + d.maj2 + "\n" + d.maj2_attendance + "\n" + d.maj3 + "\n" + d.maj3_attendance + "\n" + d.min1 + "\n" + d.min1_attendance + "\n" + d.min2 + "\n" + d.min2_attendance + "\n" + d.min3 + "\n" + d.min3_attendance + "\n" + d.hallDuePaid + d.eligibility + "\n" + d.transactionID + "\n" + d.paymentClear + "\n");
            writer.flush();
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(SignUpWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }

    private void fetchDataButtonMouseClicked(java.awt.event.MouseEvent evt) {
        try {
            int n = Integer.parseInt(jTextField1.getText());

            data d = sdata.get(n);

            nameTextField.setText(d.name);
            yearTextField.setText(d.year);
            hallTextField.setText(d.hall);
            deptTextField.setText(d.department);
            semesterTextField.setText(d.semester);
        } catch (Exception e) {
        }
    }

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        // TODO add your handling code here:
        try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to logout?", "Confirmation!", dialogButton);
            if (dialogResult == 0) {
                LoginWindow l1 = new LoginWindow();
                l1.setVisible(true);

                dispose();

            } else {
                System.out.println("Not sure");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void loadServerDataButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadServerDataButtonMouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to load data from server?\nYou can do it only once", "Warning!", dialogButton);
        if (dialogResult == 0) {

            SimpleClient sc = new SimpleClient();
            sdata = sc.receive(2007);

            JOptionPane.showMessageDialog(rootPane, "Data loaded from Server");
        } else {
            System.out.println("Data Not Loaded");
        }     // TODO add your handling code here:
    }//GEN-LAST:event_loadServerDataButtonMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to submit your data?", "Warning!", dialogButton);
        if (dialogResult == 0) {
            SimpleClient sc = new SimpleClient();
            sc.sendh(sdata, 2014);
            JOptionPane.showMessageDialog(rootPane, "All data has been forwarded to server");
        } else {
            System.out.println("Not sure");
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void helpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Firstly you have to load data from server. Then you can fetch data of any specific roll.\nAfter confirming payment information store it and then forward it to server.");
    }//GEN-LAST:event_helpButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamControllerOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamControllerOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamControllerOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamControllerOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamControllerOffice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deptTextField;
    private javax.swing.JButton fetchDataButton;
    private javax.swing.JTextField hallTextField;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loadServerDataButton;
    private javax.swing.JButton logOutButton;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JCheckBox paymentCheckBox;
    private javax.swing.JTextField semesterTextField;
    private javax.swing.JButton storeButton;
    private javax.swing.JTextField trxIDTextField;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables
}
