/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smartx.du;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author saif_m_dhrubo
 */
public class HallOffice extends javax.swing.JFrame {

    public static HashMap<Integer, data> sdata = new HashMap<>();

    /**
     * Creates new form HallOffice
     */
    public HallOffice() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox6 = new javax.swing.JComboBox<>();
        helpButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        hallName = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        dept = new javax.swing.JComboBox<>();
        session_FormattedTextField = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        yearComboBox = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        semesterComboBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        residencyComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        hallPaymentCheckBox = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fetchDataButton = new javax.swing.JButton();
        roll = new javax.swing.JTextField();
        storeButton = new javax.swing.JButton();
        getServerDataButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        helpButton1 = new javax.swing.JButton();

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Non-Resident", "Resident" }));

        helpButton.setText("Help");
        helpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(130, 47, 36));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Residential Hall Office");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel11.setText("Name of Residential Hall");

        hallName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shahidullah Hall", "Fazlul Haq Muslim Hall", "Amar Ekushey Hall", "Jagannath Hall", "Sufia Kamal Hall", "Rokeya Hall" }));

        jLabel2.setText("Department");

        dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science and Engineering", "IBA", "Pharmacy", "IIT", "Genetic Engineering and Biotechnology", "Nuclear Engineering", "Robotics and Mechatronics Engineering", "Electrical and Electronic Engineering", "MIcrobiology", "Applied Chemistry and Chemical Engineering", "Finance", "Economics", "International Relations", "Public Administration", "English Literature", "Marketing", "Mass Communication and Journalism", "Political Science", "Development Studies", "Law", " ", " ", " ", " " }));
        dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptActionPerformed(evt);
            }
        });

        try {
            session_FormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Session");

        jLabel3.setText("Class  Roll No.");

        jLabel12.setText("Select Year (B.Sc.)");

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd", "3rd", "4th" }));

        jLabel13.setText("Select Semester");

        semesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st", "2nd" }));

        jLabel4.setText("Residential Status");

        residencyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Non-Resident", "Resident" }));

        jLabel7.setText("(If Resident) Room no.");

        hallPaymentCheckBox.setText("Hall Office Dues Paid");

        jButton1.setText("Forward to Server");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        fetchDataButton.setText("Fetch Data");
        fetchDataButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fetchDataButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fetchDataButtonMouseClicked(evt);
            }
        });

        storeButton.setText("Store");
        storeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        storeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                storeButtonMouseClicked(evt);
            }
        });

        getServerDataButton.setText("Get Data From Server");
        getServerDataButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getServerDataButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getServerDataButtonMouseClicked(evt);
            }
        });

        logOutButton.setText("Log Out");
        logOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
        });

        helpButton1.setText("Help");
        helpButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(storeButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(session_FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hallPaymentCheckBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(residencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hallName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(roll, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(fetchDataButton)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logOutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(helpButton1)
                        .addGap(20, 20, 20)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(getServerDataButton)
                .addGap(293, 293, 293))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton1)
                .addGap(19, 19, 19)
                .addComponent(getServerDataButton)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fetchDataButton))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(hallName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(session_FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(semesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(residencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hallPaymentCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(logOutButton))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptActionPerformed

    private void fetchDataButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fetchDataButtonMouseClicked
        try {
           int n = Integer.parseInt(roll.getText());

        data d = sdata.get(n);

        hallName.setSelectedItem(d.hall);
        dept.setSelectedItem(d.department);
        session_FormattedTextField.setText(d.session);
        yearComboBox.setSelectedItem(d.year);
        semesterComboBox.setSelectedItem(d.semester); 
        } catch (Exception e) {
        }
 

    }//GEN-LAST:event_fetchDataButtonMouseClicked

    private void storeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_storeButtonMouseClicked
        try {
           
  int n = Integer.parseInt(roll.getText());

        data d = sdata.get(n);

        d.residentialStatus = (String) residencyComboBox.getSelectedItem();
        if (hallPaymentCheckBox.isSelected()) {
            d.hallDuePaid = true;
        }

        d.roomNumber = jTextField1.getText();
        
        sdata.put(n, d); 
        
         String path = "/home/saif_m_dhrubo/SmartX Du/StudentInfo/" + String.valueOf(n) + ".txt";
                System.out.println(path);
                File f = new File(path);

                try {
                    f.createNewFile();
                } catch (IOException ex) {
                    Logger.getLogger(SignUpWindow.class.getName()).log(Level.SEVERE, null, ex);
                }

                FileWriter writer;
                try {
                    writer = new FileWriter(f);
          writer.write(   d.roll+ "\n" +  d.regnum+ "\n" + d.session+ "\n" + d.department+ "\n" +  d.name+ "\n" + d.father+ "\n" +  d.mother+ "\n" +d.dob+ "\n" +   d.username+ "\n" +d.password+ "\n" + d.hall+ "\n" +d.year+ "\n" +  d.semester+ "\n" + d.email+ "\n" +d.residentialStatus+ "\n" + d.roomNumber+ "\n" +  d.maj1+ "\n" + d.maj1_attendance+ "\n" + d.maj2+ "\n" + d.maj2_attendance+ "\n" +  d.maj3+ "\n" + d.maj3_attendance+ "\n" + d.min1+ "\n" +d.min1_attendance+ "\n" +  d.min2+ "\n" + d.min2_attendance+ "\n" +d.min3+ "\n" + d.min3_attendance+ "\n" +  d.hallDuePaid +   d.eligibility + "\n" +    d.transactionID+ "\n" +d.paymentClear+ "\n");
         writer.flush();
                    writer.close();
                } catch (IOException ex) {
                    Logger.getLogger(SignUpWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        } catch (Exception e) {
        }
    }//GEN-LAST:event_storeButtonMouseClicked

    private void getServerDataButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getServerDataButtonMouseClicked
     int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to load data from server?\nYou can do it only once", "Warning!", dialogButton);
        if (dialogResult == 0) {

        SimpleClient sc = new SimpleClient();
        sdata = sc.receive(2006);

            JOptionPane.showMessageDialog(rootPane, "Data loaded from Server");
        } else {
            System.out.println("Data Not Loaded");
        }  
        
    }//GEN-LAST:event_getServerDataButtonMouseClicked

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        // TODO add your handling code here:
              try {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to logout?", "Confirmation!", dialogButton);
            if (dialogResult == 0) {
            LoginWindow l1 = new LoginWindow();
        l1.setVisible(true);

        dispose();
          
      
            } else {
                System.out.println("Not sure");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure to submit your data?", "Warning!", dialogButton);
        if (dialogResult == 0) {
            SimpleClient sc = new SimpleClient();
            sc.sendh(sdata, 2003);
             JOptionPane.showMessageDialog(rootPane, "All data has been forwarded to server");
        } else {
            System.out.println("Not sure");
        }     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void helpButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButton1MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Firstly you have to load data from server. Then you can fetch data of any specific roll. After confirming hall payment store it and then forward it to server.");
    }//GEN-LAST:event_helpButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HallOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HallOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HallOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HallOffice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HallOffice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dept;
    private javax.swing.JButton fetchDataButton;
    private javax.swing.JButton getServerDataButton;
    private javax.swing.JComboBox<String> hallName;
    private javax.swing.JCheckBox hallPaymentCheckBox;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton helpButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JComboBox<String> residencyComboBox;
    private javax.swing.JTextField roll;
    private javax.swing.JComboBox<String> semesterComboBox;
    private javax.swing.JFormattedTextField session_FormattedTextField;
    private javax.swing.JButton storeButton;
    private javax.swing.JComboBox<String> yearComboBox;
    // End of variables declaration//GEN-END:variables
}
